### ISSUE TITLE
INTERNAL PED

### ISSUE THREAD

**Issue by justinyjt** [AY2122S2-CS2103T-T17-1/tp#273]
Simulate PE-D and report any findings here!

Best to follow a format like

## [<Docs/Bug/Flaw>-<specifics>-[additional detail]] <Descriptive one-liner of issue>

Severity: <High, Medium, Low, Very Low>

<Details such as steps to reproduce or screenshots>

[Suggestions]
Click here to view the examples
[Docs-UG-Add] Invalid sample command for add.
Severity: Very low

Sample command was missing one mandatory field.

[Bug-Find] Separator value does not work.
Severity: Medium

Find command allows searching of values separated by commas, but the input does not seem to be separated.

Steps to reproduce:

find test, abc
Returns an error message saying unable to "test, abc". (can include screenshot)
Suggestion:

Check if the user input that is parsed splits by commas,
otherwise update the UG and sample commands to indicate how values are separated. hi
Massive shout out to everyone who took part in this! ❤️

**Comment by xpzmichael** [comment]
<img width="729" alt="Screen Shot 2022-04-08 at 18 03 42" src="https://user-images.githubusercontent.com/77215508/162414126-64f162f8-d222-4099-b7ff-e20ffeda9358.png">
long address cannot be shown fully on devices with small screen size.

**Comment by xpzmichael** [comment]
<img width="443" alt="Screen Shot 2022-04-08 at 18 05 16" src="https://user-images.githubusercontent.com/77215508/162414382-6c2544ba-2ac7-455f-93ad-3d613d9fd07d.png">
Same number and email for different companies is allowed. Maybe identical number and email should throw a error similar to duplicate company name?

**Comment by xpzmichael** [comment]
<img width="285" alt="Screen Shot 2022-04-08 at 18 23 32" src="https://user-images.githubusercontent.com/77215508/162417488-2a0355dd-33e4-4a85-bbf0-98ca5063980a.png">
Maybe consider to remove the old reminders when the time has already passed since it will not be used anymore.

**Comment by atmh** [comment]
[Flaw] No handling for corrupted save file.
Severity: High
Steps to reproduce: 
1. Edit the JSON save file with an invalid character. E.g. "@" in name
2. Launch Tinner
3. `list`
4. **poof**

There doesn't seem to be a backfile file.

Suggestions:
Create a backup file if the save file is corrupted.

**Comment by atmh** [comment]
[Flaw] Commands that do not take in parameters still executes if parameters are provided.
Severity: High
Steps to reproduce: 
1. `clear 1`

Expected: Invalid command message as there are trailing characters.
Actual: `clear` executes.

Reasoning: Imagine a user wants to delete something at index 1, and mistakenly use `clear` instead. He executes `clear 1` and everything is gone :(. Especially since there is no undo feature, there is a need to prevent such cases from happening.

**Comment by atmh** [comment]
[Docs] 
Severity: Low

![image](https://user-images.githubusercontent.com/77260849/162429082-80c3b221-1f09-4745-8ff4-59d6591d5872.png)


![image](https://user-images.githubusercontent.com/77260849/162429293-ed240d02-9163-4a51-813d-38870ddb60e2.png)


Example provided in the command summary does not work.

**Comment by lovemathboy** [comment]
[Docs]

The idea of Demo Use Cases is a great idea, however, since the intent is for users to follow alongside it, it may be good to include a copy of the command executed alongside the demo. 

E.g. Changing Use Case 1 Step 1 to: 
[Add the company](https://ay2122s2-cs2103t-t17-1.github.io/tp/UserGuide.html#c-add-c) to the company list via the following command: `addCompany n/Gov Tech e/areyouit@tech.gov.sg`
instead of 
<img width="755" alt="Screen Shot 2022-04-08 at 7 16 00 PM" src="https://user-images.githubusercontent.com/22218752/162425287-7e2f47a0-a09f-4465-a16b-f7f4b084dce1.png">

This is especially true for Step 2 of Use Case 1 of adding a role where the full command is cut-off.
<img width="766" alt="Screen Shot 2022-04-08 at 7 51 11 PM" src="https://user-images.githubusercontent.com/22218752/162430217-f33d7073-2382-4d81-b9be-3b213f0007b9.png">

**Comment by atmh** [comment]
[Flaw] Duplicate detection for company name
Severity: Medium

Steps to reproduce:
<pre>
Step 1: `addCompany n/Google Hire Me Pls`
Step 2: `addCompany n/Google Hire Me      Pls`
</pre>

Intuitively, these 2 companies should be the same even though there is a difference in white space.

Suggestion:
Trim extra white spaces between words to a single white space.

**Comment by lovemathboy** [comment]
[Bug] Valid role name is rejected.
Severity: Medium

The command `addRole 1 n/(Front end) Software Engineer s/pending` is rejected:
<img width="696" alt="Screen Shot 2022-04-08 at 7 57 48 PM" src="https://user-images.githubusercontent.com/22218752/162431652-c38a386e-f201-43e9-8a0d-0030581e16a1.png">

According to the User Guide and the Error message, the only specification is that there can be at most 1 pair of round brackets and they must be paired. However, upon further testing, the following commands all follow the format specified in the User Guide/Error Message but are all rejected:

`addRole 1 n/(Front end) Software Engineer s/pending` (Round brackets at the start)
`addRole 1 n/Software (Developer) Engineer s/pending` (Round brackets in the middle)
`addRole 1 n/(Software Engineer) s/pending` (The entire text is surrounded in the round bracket)

Suggestion:
Either specify where the round brackets are valid in the UG/Error Message or allow the round brackets to be everywhere in the code.

In addition, the UG is pretty messy in terms of role specifications, as it's displayed once in addRole and once under Role Restrictions (which is linked to from editRole, but not by addRole). I'm not sure what's the best way of fixing this but one way would be to just have a Role Restrictions section and have everything link there.

[very minor] `addRole 1 n/Software Developer Engineer () s/pending` is valid, if you wish, you can disallow empty ()s.

**Comment by lovemathboy** [comment]
[Docs] Ensure you have valid examples in the docs
Severity: Medium

I deleted companyList.json and relaunched the app to get the default internships at the beginning.
Then, I copied the command `editRole 1 1 s/pending b/31-03-2022 23:59 $/5000` from the Command Summary section of the UG.

It produces the following error:
<img width="695" alt="Screen Shot 2022-04-08 at 8 19 51 PM" src="https://user-images.githubusercontent.com/22218752/162434632-a296d11f-8177-426e-93a9-067717a347e1.png">

As a user, I was very confused because the command looks perfectly fine, why was "pending" rejected as a status – it's clearly written in the error message as a valid status?

The bug is because `b/` is not a valid prefix.

Suggestion:
Change all `b/` to `r/`.
Change the date of the reminder to someday after the actual PE so you can defend against those bugs.
